import { Domain, Course, Review, User, Enquiry, Enrollment, BlogPost, EventItem, SiteSettings, StudentNotification } from './types';

export const INITIAL_DOMAINS: Domain[] = [
  {
    id: 'dom-1',
    name: 'Information Technology',
    slug: 'information-technology',
    headline: 'Master full stack, backend, cloud, devops & enterprise software architectures.',
    description: 'Comprehensive software engineering programs covering React, Next.js, Node.js, Python, Java, AWS, Kubernetes & Cyber Security.',
    iconName: 'Code',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      'Full Stack Development',
      'Frontend Development',
      'Backend Development',
      'Python Development',
      'Java Development',
      'Software Testing',
      'Cloud Computing',
      'DevOps',
      'Cyber Security',
      'Database Development',
    ],
    featured: true,
    courseCount: 4,
  },
  {
    id: 'dom-2',
    name: 'Artificial Intelligence & Machine Learning',
    slug: 'ai-machine-learning',
    headline: 'Build generative AI, LLM agents, deep learning & intelligent automation.',
    description: 'Master PyTorch, Transformers, Prompt Engineering, OpenAI APIs, Computer Vision, NLP & Autonomous AI Agents.',
    iconName: 'BrainCircuit',
    image: 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      'Generative AI',
      'AI Tools',
      'Machine Learning',
      'Deep Learning',
      'Prompt Engineering',
      'AI Automation',
      'AI for Business',
      'Computer Vision',
      'NLP',
      'AI Agents',
    ],
    featured: true,
    courseCount: 3,
  },
  {
    id: 'dom-3',
    name: 'Data & Analytics',
    slug: 'data-analytics',
    headline: 'Transform raw data into business strategy with Power BI, SQL, Python & Advanced Excel.',
    description: 'Learn data storytelling, business intelligence, predictive metrics, ETL pipelines, and statistical decision frameworks.',
    iconName: 'BarChart3',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      'Data Analytics',
      'Business Analytics',
      'Excel',
      'Advanced Excel',
      'Power BI',
      'SQL',
      'Data Visualization',
      'Statistics',
      'Business Intelligence',
    ],
    featured: true,
    courseCount: 3,
  },
  {
    id: 'dom-4',
    name: 'Digital Marketing',
    slug: 'digital-marketing',
    headline: 'Scale brands with Google Ads, Meta Ads, SEO, Performance & Influencer Marketing.',
    description: 'Master conversion optimization, lead generation funnels, content strategies, email campaigns & marketing analytics.',
    iconName: 'Megaphone',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      'SEO',
      'Social Media Marketing',
      'Google Ads',
      'Meta Ads',
      'Content Marketing',
      'Email Marketing',
      'Affiliate Marketing',
      'Performance Marketing',
      'Influencer Marketing',
      'Marketing Analytics',
    ],
    featured: true,
    courseCount: 2,
  },
  {
    id: 'dom-5',
    name: 'UI/UX & Design',
    slug: 'ui-ux-design',
    headline: 'Craft modern web/mobile products with Figma, UX research & design systems.',
    description: 'Learn visual hierarchy, wireframing, interactive prototyping, usability testing, and build portfolio case studies.',
    iconName: 'Palette',
    image: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      'UI Design',
      'UX Design',
      'Figma',
      'Graphic Design',
      'Design Thinking',
      'Prototyping',
      'Wireframing',
      'Interaction Design',
      'Brand Design',
      'Portfolio Development',
    ],
    featured: true,
    courseCount: 2,
  },
  {
    id: 'dom-6',
    name: 'Management & Business',
    slug: 'management-business',
    headline: 'Lead high-performing teams, product roadmaps & strategic business operations.',
    description: 'Programs in Product Management, Agile PMP, Leadership, Entrepreneurship & Sales Management.',
    iconName: 'Briefcase',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      'Business Management',
      'Project Management',
      'Product Management',
      'Human Resource Management',
      'Business Communication',
      'Entrepreneurship',
      'Operations Management',
      'Sales Management',
      'Leadership',
      'Business Strategy',
    ],
    featured: true,
    courseCount: 2,
  },
  {
    id: 'dom-7',
    name: 'Finance & Accounting',
    slug: 'finance-accounting',
    headline: 'Master Tally Prime, GST filing, financial modeling, corporate valuation & Excel.',
    description: 'Practical training in balance sheets, income tax returns, investment analysis, and corporate finance frameworks.',
    iconName: 'Calculator',
    image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      'Financial Accounting',
      'Tally',
      'GST',
      'Income Tax',
      'Financial Modeling',
      'Investment Basics',
      'Banking',
      'Corporate Finance',
      'Accounting with Excel',
      'Financial Analysis',
    ],
    featured: true,
    courseCount: 2,
  },
  {
    id: 'dom-8',
    name: 'Communication & Professional Skills',
    slug: 'communication-professional-skills',
    headline: 'Elevate spoken English, interview confidence, public speaking & workplace etiquette.',
    description: 'Comprehensive soft skills training covering business English, presentation mastery, GD drills, and resume writing.',
    iconName: 'MessageSquare',
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      'Spoken English',
      'Business English',
      'Personality Development',
      'Interview Preparation',
      'Presentation Skills',
      'Public Speaking',
      'Resume Building',
      'Group Discussion',
      'Workplace Communication',
      'Soft Skills',
    ],
    featured: true,
    courseCount: 2,
  },
  {
    id: 'dom-9',
    name: 'Emerging Technologies',
    slug: 'emerging-technologies',
    headline: 'Explore Blockchain, Web3, IoT, Robotics, AR/VR & n8n AI Workflow Automation.',
    description: 'Stay ahead of technological shifts with hands-on practice in decentralization, smart contracts & low-code automation.',
    iconName: 'Cpu',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      'Blockchain',
      'Web3',
      'IoT',
      'AR/VR',
      'Robotics',
      'Cloud Technologies',
      'Automation',
      'No-Code / Low-Code',
      'n8n Automation',
      'Future Technologies',
    ],
    featured: true,
    courseCount: 2,
  },
  {
    id: 'dom-10',
    name: 'Career & Professional Programs',
    slug: 'career-professional-programs',
    headline: 'Guaranteed 100% Job-Oriented Bootcamps, Internships & Placement Prep Tracks.',
    description: 'Fast-track career switchers, freshers & professionals into tier-1 enterprise employment with 1-on-1 mentorship.',
    iconName: 'GraduationCap',
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      'Job-Oriented Programs',
      'Internship Programs',
      'Certification Programs',
      'Career Switch Programs',
      'Placement Preparation',
      'Fresher Programs',
      'Professional Upskilling',
      'Corporate Training',
      'Short-Term Programs',
      'Career Guidance',
    ],
    featured: true,
    courseCount: 2,
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-1',
    title: 'Full Stack MERN & Next.js Masterclass',
    slug: 'full-stack-mern-nextjs-masterclass',
    headline: 'Become a job-ready Full Stack Engineer with React, Next.js 14, Node.js & PostgreSQL',
    description: 'This comprehensive 6-month flagship program covers everything from foundational HTML/CSS/JavaScript to advanced microservices, Next.js server components, database design, Docker, and CI/CD pipelines. Includes 4 capstone projects and 100% placement support.',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1000&auto=format&fit=crop',
    domainId: 'dom-1',
    domainName: 'Information Technology',
    domainSlug: 'information-technology',
    duration: '6 Months',
    fee: 45000,
    discountFee: 34999,
    level: 'Beginner to Advanced',
    mode: 'Live Online + Classroom Hybrid',
    badge: 'Flagship Bestseller',
    categoryTag: 'TRENDING',
    rating: 4.9,
    totalStudents: 1420,
    placementAssistance: true,
    featured: true,
    highlights: [
      '100% Placement Assistance with 40+ Hiring Partners',
      '4 Industry-Grade Real World Capstone Projects',
      '1-on-1 Code Reviews & Mentorship from Senior Engineers',
      'Comprehensive System Design & DSA Prep Included',
    ],
    instructor: {
      name: 'Rohan Deshmukh',
      title: 'Ex-Senior Staff Engineer at Amazon',
      experience: '11+ Years Experience in Full Stack & Cloud Architectures',
      expertise: ['React 18', 'Next.js 14', 'Node.js', 'System Design', 'PostgreSQL'],
      photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
      linkedin: 'https://linkedin.com',
    },
    prerequisites: [
      'Basic understanding of computer fundamentals',
      'No prior coding experience required; course starts from HTML/CSS scratch',
    ],
    whoShouldTake: [
      'College students and fresh graduates seeking tier-1 software engineer jobs',
      'Working IT professionals wanting to switch to Full Stack Web Development',
      'Career switchers moving from non-tech backgrounds into coding',
    ],
    toolsCovered: ['HTML5', 'CSS3', 'Tailwind CSS', 'JavaScript ES6+', 'React 18', 'Next.js 14', 'Node.js', 'Express', 'PostgreSQL', 'Prisma ORM', 'Docker', 'Git'],
    projects: [
      {
        title: 'Full-Stack E-Commerce Platform with Next.js & Stripe',
        description: 'Complete online marketplace with server-rendered product listing, cart state, secure payment checkout, and admin order panel.',
        techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Prisma', 'PostgreSQL'],
      },
    ],
    faqs: [
      {
        question: 'Will I get guaranteed placement calls after completing this course?',
        answer: 'Yes! Our dedicated placement cell conducts resume auditing, mock technical interviews, and direct referral drives until you receive job offers.',
      },
    ],
    careerRoles: [
      {
        title: 'Full Stack Engineer',
        avgSalary: '₹6.5 LPA - ₹16 LPA',
        hiringCompanies: ['Amazon', 'Swiggy', 'Zomato', 'Paytm'],
      },
    ],
    syllabus: [
      {
        moduleNumber: 1,
        title: 'Module 1 — Foundational Web Architecture & Responsive UI',
        duration: '4 Weeks',
        topics: [
          'Semantic HTML5 & Accessibility Standards',
          'Flexbox & CSS Grid Responsive Layout Systems',
          'Tailwind CSS 3 Utility-First Design Systems',
          'Git & GitHub Team Collaboration & Branching Workflows',
        ],
        practicalLab: 'Responsive Corporate Tech Agency Portal & Portfolio',
      },
      {
        moduleNumber: 2,
        title: 'Module 2 — Modern JavaScript ES6+ & Asynchronous Engine',
        duration: '4 Weeks',
        topics: [
          'JavaScript Event Loop & Execution Context',
          'Promises, Async/Await & Fetch API',
          'DOM Manipulation & Event Handling',
          'Object-Oriented & Functional JS Patterns',
        ],
        practicalLab: 'Interactive Drag-and-Drop Kanban Task Board App',
      },
      {
        moduleNumber: 3,
        title: 'Module 3 — Frontend Engineering with React 18 & State',
        duration: '4 Weeks',
        topics: [
          'React 18 Component Architecture & JSX',
          'useState, useEffect, useMemo, useCallback Hooks',
          'Global State Management with Context API & Zustand',
          'React Router v6 & Dynamic Routing',
        ],
        practicalLab: 'Live Video Analytics Dashboard with Real-time Charts',
      },
      {
        moduleNumber: 4,
        title: 'Module 4 — Full Stack Next.js 14 App Router & SSR',
        duration: '4 Weeks',
        topics: [
          'Next.js 14 App Router Architecture',
          'Server Components (RSC) vs Client Components',
          'Server Actions & Form Mutations',
          'NextAuth.js Multi-Provider User Authentication',
        ],
        practicalLab: 'Full Stack SaaS Subscription Application',
      },
      {
        moduleNumber: 5,
        title: 'Module 5 — Backend REST APIs, PostgreSQL & Express',
        duration: '4 Weeks',
        topics: [
          'Node.js Server Architecture & Express REST APIs',
          'PostgreSQL Relational Database Schema Design',
          'Prisma ORM & Migration Workflows',
          'JWT Authentication, Rate Limiting & Security',
        ],
        practicalLab: 'Scalable Banking Wallet & Payment Microservice API',
      },
      {
        moduleNumber: 6,
        title: 'Module 6 — System Design, Cloud DevOps & Placement Prep',
        duration: '4 Weeks',
        topics: [
          'Docker Containerization & Multi-Container Setup',
          'AWS EC2, S3 & Cloudflare Deployment',
          'CI/CD Automated Pipelines with GitHub Actions',
          'System Design, DSA Prep & Mock Technical Interviews',
        ],
        practicalLab: 'Production Capstone: Multi-Vendor E-Commerce Platform with Stripe',
      },
    ],
  },
  {
    id: 'course-2',
    title: 'Generative AI & LLM Agent Engineering',
    slug: 'generative-ai-llm-agent-engineering',
    headline: 'Master Python, PyTorch, LangChain, RAG Architecture & OpenAI Agents',
    description: 'Learn how to fine-tune transformers, build vector search databases (Pinecone, Chroma), engineer custom RAG pipelines, and deploy autonomous AI agents for enterprise business workflows.',
    image: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?q=80&w=1000&auto=format&fit=crop',
    domainId: 'dom-2',
    domainName: 'Artificial Intelligence & Machine Learning',
    domainSlug: 'ai-machine-learning',
    duration: '6 Months',
    fee: 55000,
    discountFee: 42999,
    level: 'Beginner to Advanced',
    mode: 'Live Interactive Online',
    badge: 'High Demand Tech',
    categoryTag: 'JOB_ORIENTED',
    rating: 4.9,
    totalStudents: 980,
    placementAssistance: true,
    featured: true,
    highlights: [
      'Build 5 Autonomous LLM & RAG Applications',
      'Master PyTorch, Hugging Face Transformers & LangChain',
    ],
    instructor: {
      name: 'Dr. Ananya Sen',
      title: 'Lead AI Researcher & Ex-Google AI Fellow',
      experience: '9+ Years Experience in Machine Learning & LLM Orchestration',
      expertise: ['PyTorch', 'LangChain', 'RAG Pipelines', 'OpenAI API', 'HuggingFace'],
      photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop',
      linkedin: 'https://linkedin.com',
    },
    prerequisites: ['Basic Python programming knowledge helpful'],
    whoShouldTake: ['Data Scientists wanting to specialize in GenAI & LLM agent engineering'],
    toolsCovered: ['Python', 'PyTorch', 'LangChain', 'LlamaIndex', 'Pinecone'],
    projects: [
      {
        title: 'Enterprise PDF Document Q&A RAG System',
        description: 'Retrieval-Augmented Generation engine allowing users to upload corporate PDFs.',
        techStack: ['Python', 'LangChain', 'ChromaDB', 'OpenAI GPT-4'],
      },
    ],
    faqs: [
      {
        question: 'Do I need a GPU computer to attend live lab sessions?',
        answer: 'No, Apex Institute provides cloud GPU sandbox environments for all students.',
      },
    ],
    careerRoles: [
      {
        title: 'AI Solutions Engineer',
        avgSalary: '₹9.5 LPA - ₹24 LPA',
        hiringCompanies: ['Google', 'Microsoft', 'NVIDIA'],
      },
    ],
    syllabus: [
      {
        moduleNumber: 1,
        title: 'Module 1 — Python for AI, NumPy & PyTorch Tensors',
        duration: '4 Weeks',
        topics: ['NumPy Matrices & Linear Algebra', 'Pandas Exploratory Data Analysis', 'PyTorch Tensors & GPU Acceleration'],
        practicalLab: 'High-Performance Tensor Compute Engine',
      },
      {
        moduleNumber: 2,
        title: 'Module 2 — Neural Networks & Deep Learning Foundations',
        duration: '4 Weeks',
        topics: ['Backpropagation & Loss Functions', 'Convolutional Neural Networks (CNNs)', 'Recurrent Networks & Attention Mechanics'],
        practicalLab: 'Computer Vision Medical Image Classifier',
      },
      {
        moduleNumber: 3,
        title: 'Module 3 — Hugging Face Transformers & Language Models',
        duration: '4 Weeks',
        topics: ['Transformer Self-Attention', 'Hugging Face Pipelines & Models', 'Tokenizers & Positional Encoding'],
        practicalLab: 'Domain-Specific Sentiment & Entity Extraction Engine',
      },
      {
        moduleNumber: 4,
        title: 'Module 4 — Vector Databases & Enterprise RAG Systems',
        duration: '4 Weeks',
        topics: ['Embeddings & Cosine Similarity', 'Pinecone & Chroma Vector DBs', 'LangChain & LlamaIndex Orchestration'],
        practicalLab: 'Enterprise PDF Knowledgebase RAG System',
      },
      {
        moduleNumber: 5,
        title: 'Module 5 — Autonomous AI Agent Architecture',
        duration: '4 Weeks',
        topics: ['ReAct Prompting & Tool Calling', 'Multi-Agent Frameworks (CrewAI, AutoGen)', 'Memory & Long-term Context Management'],
        practicalLab: 'Autonomous AI Market Research & Report Writer Agent',
      },
      {
        moduleNumber: 6,
        title: 'Module 6 — Fine-Tuning LLMs, Quantization & Cloud Deployment',
        duration: '4 Weeks',
        topics: ['PEFT / LoRA Fine-Tuning', 'vLLM & Ollama Local Serving', 'Docker & AWS SageMaker AI Deployment'],
        practicalLab: 'Production-Grade Fine-Tuned Llama-3 AI Assistant',
      },
    ],
  },
  {
    id: 'course-3',
    title: 'Business Analytics & Power BI Masterclass',
    slug: 'business-analytics-power-bi-masterclass',
    headline: 'Master Advanced Excel, SQL, Power BI Dashboards & Data Visualization',
    description: 'Transform complex business datasets into actionable strategy dashboards. Learn SQL querying, DAX measures, automated reporting pipelines, and business metrics forecasting.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1000&auto=format&fit=crop',
    domainId: 'dom-3',
    domainName: 'Data & Analytics',
    domainSlug: 'data-analytics',
    duration: '4 Months',
    fee: 38000,
    discountFee: 28999,
    level: 'Beginner Friendly',
    mode: 'Live Online + Self-Paced Labs',
    badge: 'Top Rated',
    categoryTag: 'POPULAR',
    rating: 4.8,
    totalStudents: 1100,
    placementAssistance: true,
    featured: true,
    highlights: [
      'Master Power BI Desktop, DAX & SQL Queries',
      'Build 6 Live Interactive Executive Dashboards',
    ],
    instructor: {
      name: 'Kavita Nair',
      title: 'Lead Analytics Manager at Deloitte',
      experience: '8+ Years in Business Intelligence & SQL Analytics',
      expertise: ['Power BI', 'DAX', 'SQL Server', 'Advanced Excel'],
      photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&auto=format&fit=crop',
    },
    prerequisites: ['No prior technical knowledge needed; starts with Excel fundamentals'],
    whoShouldTake: ['BBA, BCA, Commerce graduates seeking analytical analyst roles'],
    toolsCovered: ['Advanced Excel', 'SQL Server', 'Power BI Desktop', 'DAX'],
    projects: [
      {
        title: 'Executive Financial Performance Dashboard',
        description: 'Interactive Power BI dashboard tracking profit margins, revenue growth KPIs.',
        techStack: ['Power BI', 'DAX', 'SQL'],
      },
    ],
    faqs: [
      {
        question: 'Is Power BI certification included in this course?',
        answer: 'Yes, we prepare students for the official Microsoft PL-300 Power BI Analyst certification exam.',
      },
    ],
    careerRoles: [
      {
        title: 'Data Analyst / Business Analyst',
        avgSalary: '₹6.0 LPA - ₹14 LPA',
        hiringCompanies: ['Deloitte', 'KPMG', 'Accenture', 'TCS'],
      },
    ],
    syllabus: [
      {
        moduleNumber: 1,
        title: 'Module 1 — Advanced Excel Data Modeling & Automation',
        duration: '4 Weeks',
        topics: ['Nested Logical & Financial Formulas', 'XLOOKUP, INDEX-MATCH & Dynamic Arrays', 'Power Query Data Cleanse & Transformation'],
        practicalLab: 'Automated Financial & Sales Reconciliation Model',
      },
      {
        moduleNumber: 2,
        title: 'Module 2 — Enterprise SQL Querying & Database Architecture',
        duration: '4 Weeks',
        topics: ['SELECT, WHERE, GROUP BY & Joins', 'Subqueries & Common Table Expressions (CTEs)', 'Window Functions (ROW_NUMBER, DENSE_RANK)'],
        practicalLab: 'SQL Customer Churn & Cohort Retention Analysis',
      },
      {
        moduleNumber: 3,
        title: 'Module 3 — Power BI Desktop & DAX Calculations',
        duration: '4 Weeks',
        topics: ['Data Modeling & Star Schema Architecture', 'CALCULATE, FILTER & Time Intelligence DAX', 'Interactive Drill-Through & Visual Formatting'],
        practicalLab: 'Executive Regional Sales Performance Dashboard',
      },
      {
        moduleNumber: 4,
        title: 'Module 4 — Business Storytelling & PL-300 Certification',
        duration: '4 Weeks',
        topics: ['Power BI Service Cloud Deployment', 'Automated Scheduled Data Refresh', 'Microsoft PL-300 Exam Mock Preparation'],
        practicalLab: 'End-to-End Enterprise Operations Control Tower Dashboard',
      },
    ],
  },
  {
    id: 'course-6',
    title: 'Product Management & Agile Leadership',
    slug: 'product-management-agile-leadership',
    headline: 'Master Product Roadmaps, User Stories, PRDs & Agile Leadership',
    description: 'Learn how to conceptualize, validate, and launch tech products. Master wireframing, SQL metrics, A/B testing, and stakeholder alignment.',
    image: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?q=80&w=1000&auto=format&fit=crop',
    domainId: 'dom-6',
    domainName: 'Management & Business',
    domainSlug: 'management-business',
    duration: '4 Months',
    fee: 42000,
    discountFee: 31999,
    level: 'Beginner to Intermediate',
    mode: 'Live Online Studio',
    badge: 'Executive Track',
    categoryTag: 'JOB_ORIENTED',
    rating: 4.8,
    totalStudents: 650,
    placementAssistance: true,
    featured: true,
    highlights: ['Draft 3 Complete Product Requirement Documents (PRDs)', '1-on-1 Product Critique with Lead PMs'],
    instructor: {
      name: 'Manish Malhotra',
      title: 'Principal Product Manager at Swiggy',
      experience: '9+ Years Scaling Consumer Tech Apps',
      expertise: ['Product Roadmaps', 'PRD', 'Agile Scrum', 'Mixpanel'],
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
    },
    prerequisites: ['Basic problem-solving mindset; no coding required'],
    whoShouldTake: ['Aspiring Product Managers, Business Analysts, and Engineers switching to PM'],
    toolsCovered: ['Jira', 'Confluence', 'Figma', 'Mixpanel', 'Google Analytics'],
    projects: [
      {
        title: 'End-to-End SaaS Product Launch PRD',
        description: 'Create user journey maps, wireframes, pricing strategy, and success metrics for a B2B SaaS tool.',
        techStack: ['Jira', 'Figma', 'Mixpanel'],
      },
    ],
    faqs: [
      {
        question: 'Do I need a coding background for Product Management?',
        answer: 'No coding is required! Product management focuses on user problem validation and business roadmaps.',
      },
    ],
    careerRoles: [
      {
        title: 'Associate Product Manager (APM)',
        avgSalary: '₹8.0 LPA - ₹18 LPA',
        hiringCompanies: ['Swiggy', 'Razorpay', 'Flipkart'],
      },
    ],
    syllabus: [
      {
        moduleNumber: 1,
        title: 'Module 1 — User Problem Discovery & Market Opportunity',
        duration: '4 Weeks',
        topics: ['User Interview Frameworks', 'TAM / SAM / SOM Market Sizing', 'Competitive Landscape & Value Proposition'],
        practicalLab: 'User Persona & Problem Validation Benchmark Study',
      },
      {
        moduleNumber: 2,
        title: 'Module 2 — Product Requirement Documents (PRDs) & UX Wireframing',
        duration: '4 Weeks',
        topics: ['Writing Enterprise PRDs & Spec Documents', 'Figma Wireframing & User Journey Flows', 'Feature Prioritization (RICE & Kano Models)'],
        practicalLab: 'Complete PRD & Low-Fi Figma Prototype for B2B SaaS',
      },
      {
        moduleNumber: 3,
        title: 'Module 3 — Agile Scrum Execution & Engineering Alignment',
        duration: '4 Weeks',
        topics: ['Sprint Planning & Backlog Refinement', 'Jira & Confluence Project Workflows', 'Managing Engineering Dependencies & QA'],
        practicalLab: '2-Week Agile Sprint Execution Simulation',
      },
      {
        moduleNumber: 4,
        title: 'Module 4 — Product Analytics, A/B Testing & GTM Launch',
        duration: '4 Weeks',
        topics: ['Mixpanel & Amplitude Event Funnels', 'Designing A/B Experimentation Frameworks', 'Go-To-Market (GTM) Strategy & PM Interview Drills'],
        practicalLab: 'Live App Feature Conversion Optimization & GTM Pitch',
      },
    ],
  },
  {
    id: 'course-7',
    title: 'Financial Modeling & Tally Prime Certification',
    slug: 'financial-modeling-tally-prime-certification',
    headline: 'Master Tally Prime, GST Returns, Income Tax Filing & Corporate Valuation',
    description: 'Gain practical expertise in corporate balance sheets, payroll processing, GST return computation, and DCF financial valuation modeling.',
    image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=1000&auto=format&fit=crop',
    domainId: 'dom-7',
    domainName: 'Finance & Accounting',
    domainSlug: 'finance-accounting',
    duration: '3 Months',
    fee: 30000,
    discountFee: 21999,
    level: 'Beginner Friendly',
    mode: 'Live Hybrid Labs',
    badge: 'Certified Track',
    categoryTag: 'NEW',
    rating: 4.7,
    totalStudents: 520,
    placementAssistance: true,
    featured: true,
    highlights: ['Hands-on Filing of Live GST & Income Tax Returns', 'Certified Tally Prime Operator Badge'],
    instructor: {
      name: 'CA Rajesh Gupta',
      title: 'Chartered Accountant & Corporate Auditor',
      experience: '12+ Years Corporate Finance Experience',
      expertise: ['Tally Prime', 'GST', 'Financial Valuation', 'Excel'],
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop',
    },
    prerequisites: ['Basic commerce or accounts familiarity helpful'],
    whoShouldTake: ['B.Com, M.Com graduates, Accountant job seekers, and Business Owners'],
    toolsCovered: ['Tally Prime', 'Advanced Excel', 'GST Portal', 'Income Tax Utility'],
    projects: [
      {
        title: 'Corporate Financial Valuation Model',
        description: 'Build 3-statement financial models with 5-year revenue projections and DCF valuation.',
        techStack: ['Excel', 'Tally Prime'],
      },
    ],
    faqs: [
      {
        question: 'Is practical GST portal filing demonstrated during classes?',
        answer: 'Yes! Our CA instructors demonstrate live GST-1, GST-3B return filings.',
      },
    ],
    careerRoles: [
      {
        title: 'Corporate Accountant / Financial Analyst',
        avgSalary: '₹4.5 LPA - ₹9 LPA',
        hiringCompanies: ['KPMG', 'EY', 'Genpact'],
      },
    ],
    syllabus: [
      {
        moduleNumber: 1,
        title: 'Module 1 — Tally Prime Accounting & Inventory Management',
        duration: '4 Weeks',
        topics: ['Company Creation & Ledger Master Setup', 'Sales, Purchase, Payment & Receipt Vouchers', 'Stock Groups, Units & Warehouse Inventory'],
        practicalLab: 'Complete Corporate Accounts Bookkeeping Ledger',
      },
      {
        moduleNumber: 2,
        title: 'Module 2 — Statutory Taxation: GST & Income Tax Filing',
        duration: '4 Weeks',
        topics: ['CGST, SGST & IGST Invoicing Rules', 'GSTR-1, GSTR-3B Computation & Reconciliation', 'TDS Deduction Rules & Income Tax Returns'],
        practicalLab: 'Live GST & Income Tax Portal Return Filing Demonstration',
      },
      {
        moduleNumber: 3,
        title: 'Module 3 — Corporate Financial Modeling & Valuation',
        duration: '4 Weeks',
        topics: ['3-Statement Financial Model Building', 'Discounted Cash Flow (DCF) Valuation', 'Excel Financial Dashboards & Pivot Analytics'],
        practicalLab: '5-Year Corporate DCF Financial Valuation Model',
      },
    ],
  },
  {
    id: 'course-9',
    title: 'n8n & AI Workflow Automation Masterclass',
    slug: 'n8n-ai-workflow-automation-masterclass',
    headline: 'Build autonomous business workflows with n8n, OpenAI APIs & Low-Code Webhooks',
    description: 'Learn how to automate sales funnels, customer support tickets, email follow-ups, and database syncs using n8n workflows and AI LLM nodes.',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop',
    domainId: 'dom-9',
    domainName: 'Emerging Technologies',
    domainSlug: 'emerging-technologies',
    duration: '2 Months',
    fee: 28000,
    discountFee: 19999,
    level: 'Beginner to Intermediate',
    mode: 'Live Interactive Studio',
    badge: 'Future Tech',
    categoryTag: 'TRENDING',
    rating: 4.9,
    totalStudents: 410,
    placementAssistance: true,
    featured: true,
    highlights: ['Build 8 Autonomous n8n Workflow Pipelines', 'Integrate OpenAI, Slack, Airtable & PostgreSQL'],
    instructor: {
      name: 'Vikram Sethi',
      title: 'Head of Automation at TechFlow',
      experience: '6+ Years Automation Architecture',
      expertise: ['n8n', 'Zapier', 'OpenAI API', 'Webhooks', 'Make.com'],
      photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    },
    prerequisites: ['Basic internet familiarity; zero coding required'],
    whoShouldTake: ['Founders, Operations Managers, Marketers, and Tech Enthusiasts'],
    toolsCovered: ['n8n Cloud', 'OpenAI API', 'Airtable', 'Slack Webhooks', 'Make'],
    projects: [
      {
        title: 'Autonomous AI Sales Lead Qualification Agent',
        description: 'n8n pipeline that reads incoming emails, queries OpenAI for intent, updates database and dispatches WhatsApp alert.',
        techStack: ['n8n', 'OpenAI', 'Airtable'],
      },
    ],
    faqs: [
      {
        question: 'Do I need coding to build n8n workflows?',
        answer: 'No coding required! n8n uses a visual node-based drag-and-drop canvas.',
      },
    ],
    careerRoles: [
      {
        title: 'AI Automation Consultant',
        avgSalary: '₹7.0 LPA - ₹15 LPA',
        hiringCompanies: ['TechFlow', 'Zapier Agency', 'Unicorn Startups'],
      },
    ],
    syllabus: [
      {
        moduleNumber: 1,
        title: 'Module 1 — n8n Node Workflows & API Integration',
        duration: '4 Weeks',
        topics: ['n8n Visual Workflow Engine & Architecture', 'HTTP Webhook Triggers & Payload Parsing', 'Data Transformations, Branching & Retries'],
        practicalLab: 'Automated Lead Qualification & CRM Database Sync Pipeline',
      },
      {
        moduleNumber: 2,
        title: 'Module 2 — AI LLM Nodes, Multi-App Pipelines & Deployment',
        duration: '4 Weeks',
        topics: ['OpenAI & Claude LLM Agent Nodes in n8n', 'Airtable, Slack, PostgreSQL & WhatsApp Connectors', 'Self-Hosted n8n Docker Setup & Cloud Hosting'],
        practicalLab: 'Autonomous AI Customer Support & Dispatch Automation System',
      },
    ],
  },
  {
    id: 'course-10',
    title: '100% Placement Guaranteed Career Switch Track',
    slug: '100-percent-placement-career-switch-track',
    headline: 'Guaranteed 1-on-1 Mentorship, Corporate Referral Drives & Job Acceleration',
    description: 'Our premier flagship career switch program designed for graduates and working professionals changing tracks into high-paying software, data, or AI engineering jobs.',
    domainId: 'dom-10',
    domainName: 'Career & Professional Programs',
    domainSlug: 'career-professional-programs',
    duration: '6 Months',
    fee: 60000,
    discountFee: 44999,
    level: 'Beginner to Advanced',
    mode: 'Live Bootcamp + Placement Cell',
    badge: '100% Placement Call',
    categoryTag: 'JOB_ORIENTED',
    rating: 5.0,
    totalStudents: 1580,
    placementAssistance: true,
    featured: true,
    highlights: ['Guaranteed Referral Drives with 40+ Corporate Partners', 'Daily Senior Mentor Code Reviews & Mock Technical Interviews'],
    instructor: {
      name: 'Rohan Deshmukh',
      title: 'Ex-Amazon Senior Staff Engineer',
      experience: '11+ Years Full Stack Experience',
      expertise: ['Career Coaching', 'System Design', 'React', 'Node.js'],
      photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    },
    prerequisites: ['Commitment to study 15+ hours per week'],
    whoShouldTake: ['College graduates and professionals seeking guaranteed software job calls'],
    toolsCovered: ['Git', 'React', 'Next.js', 'PostgreSQL', 'Docker', 'System Design'],
    projects: [
      {
        title: 'Production SaaS Application Portfolio',
        description: 'Complete capstone project portfolio reviewed directly by hiring managers.',
        techStack: ['React', 'Next.js', 'Node.js', 'PostgreSQL'],
      },
    ],
    faqs: [
      {
        question: 'What is the placement guarantee policy?',
        answer: 'We provide direct interview calls until you secure a job offer meeting our minimum CTC threshold.',
      },
    ],
    careerRoles: [
      {
        title: 'Software Development Engineer (SDE-1)',
        avgSalary: '₹7.5 LPA - ₹18 LPA',
        hiringCompanies: ['Amazon', 'Swiggy', 'Zomato', 'Paytm'],
      },
    ],
    syllabus: [
      {
        moduleNumber: 1,
        title: 'Module 1 — Engineering Fundamentals & DSA',
        duration: '4 Weeks',
        topics: ['Data Structures', 'Algorithms', 'Big-O Notation'],
      },
    ],
  },
];

export const INITIAL_BLOGS: BlogPost[] = [
  {
    id: 'blog-1',
    title: 'How to Start a Career in Artificial Intelligence & GenAI in 2026',
    slug: 'how-to-start-career-in-ai',
    category: 'AI',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    authorName: 'Dr. Ananya Sen',
    authorTitle: 'Lead AI Fellow',
    authorPhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop',
    readTime: '6 Min Read',
    summary: 'A step-by-step roadmap for mastering Python, PyTorch, LangChain, vector databases, and RAG architectures to land high-paying AI engineering roles.',
    content: `
# How to Start a Career in Artificial Intelligence & GenAI

The landscape of software development is undergoing a generational shift. With the explosion of Large Language Models (LLMs), Retrieval-Augmented Generation (RAG), and autonomous agent networks, demand for skilled AI engineers has surged dramatically.

## 1. Master Python & Tensor Math
Python remains the undisputed language of Machine Learning. Focus your initial 4 weeks on:
- NumPy matrix transformations
- Pandas DataFrames & Exploratory Data Analysis (EDA)
- PyTorch tensor manipulation

## 2. Understand RAG Pipelines & Vector Search
Traditional LLMs hallucinate when queried on private company documents. RAG solves this by converting text into vector embeddings stored in Pinecone or ChromaDB.

## 3. Build Production LLM Projects
Employers prioritize candidates with live GitHub repositories demonstrating:
- Custom PDF Q&A bots using LangChain
- Multi-agent networks using CrewAI
- FastAPI endpoints wrapping model inference
`,
    featured: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'blog-2',
    title: 'Top 10 Full Stack Web Development Interview Questions & Answers',
    slug: 'top-full-stack-interview-questions',
    category: 'Interview Preparation',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=800&auto=format&fit=crop',
    authorName: 'Rohan Deshmukh',
    authorTitle: 'Ex-Amazon Engineer',
    authorPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    readTime: '8 Min Read',
    summary: 'Master Next.js App Router, React 18 hooks, Node.js event loop, PostgreSQL query optimization, and System Design concepts to clear tier-1 interviews.',
    content: `
# Top 10 Full Stack Web Development Interview Questions

Preparing for a senior Full Stack Engineer interview requires both theoretical depth and practical coding fluency.

## Key Focus Areas
1. React 18 Server Components vs Client Components
2. Next.js 14 Server Actions and caching mechanics
3. Relational vs Non-relational database query optimization
4. Building rate-limited JWT authentication microservices
`,
    featured: true,
    createdAt: '2026-08-05',
  },
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'evt-1',
    title: 'Live Workshop: Building Autonomous GenAI LLM Agents with LangChain',
    slug: 'live-workshop-building-autonomous-genai-agents',
    category: 'Workshops',
    date: 'Saturday, August 22, 2026',
    time: '11:00 AM - 1:30 PM IST',
    location: 'Live Zoom Studio & HSR Layout Campus',
    speakerName: 'Dr. Ananya Sen',
    speakerRole: 'Ex-Google AI Fellow',
    speakerFoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop',
    description: 'Join our hands-on live code session where we construct a multi-agent customer support bot using PyTorch, LangChain, Pinecone, and OpenAI API.',
    featured: true,
    createdAt: '2026-08-10',
  },
  {
    id: 'evt-2',
    title: 'Career Webinar: How to Transition from Non-Tech to Full Stack Coding',
    slug: 'career-webinar-non-tech-to-full-stack',
    category: 'Webinars',
    date: 'Wednesday, August 26, 2026',
    time: '7:00 PM - 8:30 PM IST',
    location: 'Live Interactive Zoom Webinar',
    speakerName: 'Rohan Deshmukh',
    speakerRole: 'Ex-Amazon Senior Engineer',
    speakerFoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    description: 'Learn the exact 6-month roadmap followed by 100+ non-tech graduates to clear technical coding rounds at top product firms.',
    featured: true,
    createdAt: '2026-08-11',
  },
];

export const INITIAL_NOTIFICATIONS: StudentNotification[] = [
  {
    id: 'notif-1',
    userId: 'usr-student-1',
    title: 'Enrollment Confirmed!',
    message: 'Welcome to Full Stack MERN & Next.js Masterclass. Your batch starts Mon-Fri at 7:30 PM.',
    type: 'ENROLLMENT',
    read: false,
    createdAt: '2026-08-10',
  },
  {
    id: 'notif-2',
    userId: 'usr-student-1',
    title: 'Live Zoom Class Scheduled',
    message: 'Next.js 14 Server Actions & Microservices live lab is today at 7:30 PM IST.',
    type: 'CLASS',
    read: false,
    createdAt: '2026-08-11',
  },
  {
    id: 'notif-3',
    userId: 'usr-student-1',
    title: 'ISO Certificate Generated',
    message: 'Your ISO 9001:2026 verified credential is now available in your dashboard.',
    type: 'CERTIFICATE',
    read: true,
    createdAt: '2026-08-08',
  },
];

export const INITIAL_SETTINGS: SiteSettings = {
  phone: '+91 9876543210',
  email: 'contact@apexinstitute.com',
  address: 'Apex Tower, Outer Ring Road, HSR Layout, Bangalore 560102',
  workingHours: 'Mon - Sat: 9:00 AM - 8:00 PM IST',
  facebookUrl: 'https://facebook.com',
  twitterUrl: 'https://twitter.com',
  linkedinUrl: 'https://linkedin.com',
  youtubeUrl: 'https://youtube.com',
  whatsappNo: '+919876543210',
};

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    userName: 'Aarav Sharma',
    userRole: 'Full Stack Engineer',
    company: 'Razorpay',
    courseId: 'course-1',
    courseTitle: 'Full Stack MERN & Next.js Masterclass',
    rating: 5,
    comment: 'The project-driven curriculum and live mentorship helped me switch careers from non-tech to a 12 LPA Full Stack role at Razorpay in just 6 months!',
    approved: true,
    createdAt: '2026-06-15',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-1',
    name: 'Admin Director',
    email: 'admin@apexinstitute.com',
    phone: '+91 9876543210',
    role: 'ADMIN',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    createdAt: '2026-01-01',
  },
  {
    id: 'usr-student-1',
    name: 'Vikram Malhotra',
    email: 'student@example.com',
    phone: '+91 9123456789',
    role: 'STUDENT',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=200&auto=format&fit=crop',
    createdAt: '2026-05-10',
  },
];

export const INITIAL_ENROLLMENTS: Enrollment[] = [
  {
    id: 'enr-1',
    userId: 'usr-student-1',
    userName: 'Vikram Malhotra',
    userEmail: 'student@example.com',
    courseId: 'course-1',
    courseTitle: 'Full Stack MERN & Next.js Masterclass',
    courseSlug: 'full-stack-mern-nextjs-masterclass',
    status: 'ACTIVE',
    progress: 65,
    batchTiming: 'Mon-Fri (7:30 PM - 9:30 PM)',
    enrolledAt: '2026-05-12',
    course: INITIAL_COURSES[0],
  },
];

export const INITIAL_ENQUIRIES: Enquiry[] = [
  {
    id: 'enq-1',
    name: 'Karan Malhotra',
    email: 'karan@gmail.com',
    phone: '+91 9811223344',
    courseId: 'course-1',
    courseTitle: 'Full Stack MERN & Next.js Masterclass',
    message: 'Interested in the upcoming weekend batch. Are installment payment options available?',
    status: 'NEW',
    notes: 'Followed up via call, requested batch syllabus PDF.',
    createdAt: '2026-08-10',
  },
];
